"""Numeric parity between the NEMS ACNet port and the real released checkpoints.

Loads fixtures (nems/../tests/fixtures/acnet_{v1.0,v2.0,v2.1}_parity.npz,
spelled with underscores on disk: acnet_v1_parity.npz, acnet_v2_0_parity.npz,
acnet_v2_1_parity.npz) generated by `ACNet_v1/data/gen_nems_parity_fixture.py
--variant {v1.0,v2.0,v2.1}` -- run separately, under the acnet_v1 conda env
(has torch), never imported here. This test loads plain numpy arrays only.

Each fixture's expected_psth was computed via
`ACNet.predict_psth_from_gtg(gtg_mag, gtg_compress='none')`, i.e. that
checkpoint's real trunk + readout (whatever compress it actually trained
with) on a fixed synthetic raw-magnitude spectrogram -- deliberately
sidestepping the raw-audio front end (level-norm + gtgram), whose numeric
parity was already established separately by direct code comparison against
nems.preprocessing.spectrogram.gammatone (see nems/preprocessing/spectrogram/
acnet_frontend.py's module docstring) and its own passing test suite.
"""
import os

import pytest
import numpy as np

from nems.models.ACNet import ACNet, load_acnet_v1_weights, pt_compress_to_nems

FIXTURE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'fixtures')
FIXTURE_PATH = {
    'v1.0': os.path.join(FIXTURE_DIR, 'acnet_v1_parity.npz'),
    'v2.0': os.path.join(FIXTURE_DIR, 'acnet_v2_0_parity.npz'),
    'v2.1': os.path.join(FIXTURE_DIR, 'acnet_v2_1_parity.npz'),
    }


def _load_fixture(version):
    path = FIXTURE_PATH[version]
    if not os.path.exists(path):
        pytest.skip(f"Fixture not found at {path} -- run "
                    f"gen_nems_parity_fixture.py --variant {version} under the "
                    "acnet_v1 env first.")
    return np.load(path)


def _build_and_load_model(fx, version):
    hidden_dim = tuple(int(h) for h in fx['hidden_dim'])
    kernel_size = [int(k) for k in fx['kernel_size']]
    model = ACNet(
        num_cfs=int(fx['num_cfs']), hidden_dim=hidden_dim, kernel_size=kernel_size,
        n_neurons=int(fx['n_neurons']), compress=pt_compress_to_nems(str(fx['compress'])),
        res_scale=float(fx['res_scale']),
        )
    # This fixture uses the same per-block key naming convention as
    # load_acnet_v1_weights's expected npz (both derive from the same
    # gen_nems_parity_fixture.py extraction logic), so the production loader
    # applies directly -- no need for a second, drifting copy of the loading
    # logic here.
    return load_acnet_v1_weights(model, FIXTURE_PATH[version])


class TestACNetParity:

    @pytest.mark.parametrize('version', ['v1.0', 'v2.0', 'v2.1'])
    def test_full_model_matches_checkpoint(self, version):
        fx = _load_fixture(version)
        model = _build_and_load_model(fx, version)

        # fx['gtg_mag'] is genuine linear (amplitude-domain) magnitude (the
        # PT-side fixture used gtg_compress='none', i.e. no undo needed
        # before PT's apply_compress) -- exactly what the standard nems
        # gtgram/acnet_gtgram returns and what this model's own first layer
        # (PowerCompress) expects directly, no domain conversion needed.
        out = model.predict(fx['gtg_mag'])
        expected = fx['expected_psth']

        assert out.shape == expected.shape
        max_abs_diff = np.max(np.abs(out - expected))
        assert np.allclose(out, expected, atol=1e-4, rtol=1e-4), (
            f"[{version}] max|diff|={max_abs_diff:.3e} vs expected psth range "
            f"[{expected.min():.3f}, {expected.max():.3f}]"
            )
