"""Numeric parity between the NEMS ACNet port and the real ACNet_v1 checkpoint.

Loads a fixture (nems/../tests/fixtures/acnet_v1_parity.npz) generated by
ACNet_v1/Claude/claude_debug/gen_nems_parity_fixture.py -- run separately,
under the acnet_v1 conda env (has torch), never imported here. This test
loads plain numpy arrays only.

The fixture's expected_psth was computed via
`ACNet.predict_psth_from_gtg(gtg_mag, gtg_compress='none')`, i.e. the
checkpoint's real trunk + readout (compress='log10x', its actual training
config) on a fixed synthetic raw-magnitude spectrogram -- deliberately
sidestepping the raw-audio front end (level-norm + gtgram), whose numeric
parity was already established separately by direct code comparison against
nems.preprocessing.spectrogram.gammatone (see nems/preprocessing/spectrogram/
acnet_frontend.py's module docstring) and its own passing test suite.
"""
import os

import pytest
import numpy as np

from nems.models.ACNet import ACNet, load_acnet_v1_weights

FIXTURE_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..', 'fixtures', 'acnet_v1_parity.npz'
    )


def _load_fixture():
    if not os.path.exists(FIXTURE_PATH):
        pytest.skip(f"Fixture not found at {FIXTURE_PATH} -- run "
                    "gen_nems_parity_fixture.py under the acnet_v1 env first.")
    return np.load(FIXTURE_PATH)


def _build_and_load_model(fx):
    hidden_dim = tuple(int(h) for h in fx['hidden_dim'])
    kernel_size = [int(k) for k in fx['kernel_size']]
    model = ACNet(
        num_cfs=int(fx['num_cfs']), hidden_dim=hidden_dim, kernel_size=kernel_size,
        n_neurons=int(fx['n_neurons']), compress=str(fx['compress']),
        res_scale=float(fx['res_scale']),
        )
    # This fixture uses the same per-block key naming convention as
    # load_acnet_v1_weights's expected npz (both derive from the same
    # gen_nems_parity_fixture.py extraction logic), so the production loader
    # applies directly -- no need for a second, drifting copy of the loading
    # logic here.
    return load_acnet_v1_weights(model, FIXTURE_PATH)


class TestACNetParity:

    def test_full_model_matches_checkpoint(self):
        fx = _load_fixture()
        model = _build_and_load_model(fx)

        # fx['gtg_mag'] is genuine linear magnitude (the PT-side fixture used
        # gtg_compress='none', i.e. no undo needed before PT's apply_compress).
        # PowerCompress's contract expects sqrt-domain input (matching NEMS's
        # own gtgram convention) -- convert domains before feeding the model.
        out = model.predict(np.sqrt(fx['gtg_mag']))
        expected = fx['expected_psth']

        assert out.shape == expected.shape
        max_abs_diff = np.max(np.abs(out - expected))
        assert np.allclose(out, expected, atol=1e-4, rtol=1e-4), (
            f"max|diff|={max_abs_diff:.3e} vs expected psth range "
            f"[{expected.min():.3f}, {expected.max():.3f}]"
            )
